#ifndef TASKS_COMMON_H_
#define TASKS_COMMON_H_

#define AHT20_TASK_STACK_SIZE 2048
#define AHT20_TASK_PRIORITY 5
#define AHT20_TASK_CORE_ID 1

// Soil Moisture Sensor
#define MOISTURE_SENSOR_TASK_STACK_SIZE 2048
#define MOISTURE_SENSOR_TASK_PRIORITY 4
#define MOISTURE_SENSOR_TASK_CORE_ID 1

// Sleep toggle button
#define SLEEP_TOGGLE_BUTTON_TASK_STACK_SIZE 1024
#define SLEEP_TOGGLE_BUTTON_TASK_PRIORITY 6
#define SLEEP_TOGGLE_BUTTON_TASK_CORE_ID 0

// AWS IOT task
#define AWS_IOT_TASK_STACK_SIZE 9216
#define AWS_IOT_TASK_PRIORITY 6
#define AWS_IOT_TASK_CORE_ID 1

#endif